"""Public service interfaces used by the Member 6 UI.

Real implementations belong to other members. The UI only depends on these
contracts (or fakes that match them).
"""

from nexa.contracts.models import (
    ActionCandidate,
    ActionItem,
    AuditEvent,
    EmailPreview,
    Employee,
    Meeting,
    RecordedAudio,
    Reminder,
    RenderedEmail,
    Role,
    SendResult,
    Transcript,
)


class AudioRecordingService:
    def start(self, source: str) -> str: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> RecordedAudio: ...


class TranscriptionService:
    def transcribe(self, audio_path: str) -> Transcript: ...


class ExtractionService:
    def extract(self, transcript: Transcript, reference_datetime=None) -> list[ActionCandidate]: ...


class PeopleService:
    def list_employees(self, query: str = "", active: str = "all") -> list[Employee]: ...
    def create_employee(self, **kwargs) -> Employee: ...
    def update_employee(self, employee_id: int, **kwargs) -> Employee: ...
    def deactivate_employee(self, employee_id: int) -> None: ...
    def list_roles(self) -> list[Role]: ...
    def create_role(self, name: str, description: str = "") -> Role: ...
    def update_role(self, role_id: int, **kwargs) -> Role: ...
    def deactivate_role(self, role_id: int) -> None: ...


class SearchService:
    def global_search(self, query: str) -> dict: ...
    def search_employees(self, query: str, filters: dict | None = None) -> list[Employee]: ...
    def search_meetings(self, query: str, filters: dict | None = None) -> list[Meeting]: ...
    def search_tasks(self, query: str, filters: dict | None = None) -> list[ActionItem]: ...


class ReportService:
    def build_meeting_report(self, meeting, actions, recipients, language) -> RenderedEmail: ...
    def build_reminder(self, employee, action, meeting, language) -> RenderedEmail: ...


class EmailPreviewService:
    def preview(self, rendered_email: RenderedEmail) -> EmailPreview: ...


class EmailSender:
    def send(self, message: RenderedEmail) -> SendResult: ...


class ReminderService:
    def list_actions(self, filters: dict | None = None) -> list[ActionItem]: ...
    def mark_complete(self, action_id: int, actor: str = "Admin") -> None: ...
    def snooze(self, reminder_id: int, new_time: str) -> None: ...
    def reschedule_action(self, action_id: int, new_due_at: str) -> None: ...
    def send_test_reminder(self, action_id: int) -> SendResult: ...
    def dashboard_counts(self) -> dict: ...


class AuditService:
    def history(self, entity_type: str | None = None) -> list[AuditEvent]: ...
    def record(self, event: AuditEvent) -> None: ...
